[[plugins]]
repo = 'Shougo/dein.vim'

#------------------------------------------------------------
# カーソル移動・スクロール
#------------------------------------------------------------

[[plugins]]
#  <Space>k : 上行移動
#  <Space>j : 下行移動
#  <Space>w : 前方単語移動
#  <Space>b : 後方単語移動
#  <Space>s : 1文字検索
repo = 'Lokaltog/vim-easymotion'
hook_add = '''
  let g:EasyMotion_keys='hjklasdfgyuiopqwertnmzxcvbHJKLASDFGYUIOPQWERTNMZXCVB'
  let g:EasyMotion_leader_key="<Space>"
  let g:EasyMotion_grouping=1
  hi  EasyMotionTarget ctermbg=none ctermfg=red
  hi  EasyMotionShade  ctermbg=none ctermfg=blue
'''

[[plugins]]
# %による対応括弧へのジャンプ機能を拡張
repo = 'tmhedberg/matchit'

[[plugins]]
# 選択範囲を('*'や'#'で)検索
repo = 'thinca/vim-visualstar'


#------------------------------------------------------------
# ファイル操作・ファイル検索
#------------------------------------------------------------

[[plugins]]
# C-t : ディレクトリをツリー表示
repo = 'scrooloose/nerdtree'
hook_add = '''
  let      NERDTreeShowHidden = 1
  nnoremap <silent><C-t> :NERDTreeToggle<CR>
  let g:NERDTreeWinSize=50
'''

[[plugins]]
# :Ack : ack検索ができる
repo = 'mileszs/ack.vim'


#--------------------------------------------------------
# 表示
#--------------------------------------------------------

[[plugins]]
# https://github.com/tpope/vim-fugitive/blob/master/doc/fugitive.txt
repo = 'tpope/vim-fugitive'

[[plugins]]
# status line
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = { 'colorscheme': 'wombat' }
    set laststatus=2
    set noshowmode

    " https://github.com/itchyny/lightline.vim/issues/390
    augroup vimrc-lightline
        autocmd VimEnter * nested call lightline#enable()
    augroup END
'''


#------------------------------------------------------------
# 編集
#------------------------------------------------------------

[[plugins]]
# コメントアウト
repo = 'tyru/caw.vim.git'

[[plugins]]
# 囲み文字の入力補助
#  囲み文字の削除 ds (delete surround)
#  囲み文字の変更 cs (change surrount)
repo = 'tpope/vim-surround'

[[plugins]]
# toml の中の vim script を検知できる
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
# toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'
