#------------------------------------------------------------
# 表示
#------------------------------------------------------------

[[plugins]]
# 変更差分を可視化
repo = 'airblade/vim-gitgutter'
on_event = ['VimEnter']
hook_post_source = '''
  nnoremap <silent> ,gg :<C-u>GitGutterToggle<CR>
  nnoremap <silent> ,gh :<C-u>GitGutterLineHighlightsToggle<CR>
  set updatetime=1000
  highlight GitGutterAdd ctermfg=black ctermbg=green
  highlight GitGutterDelete ctermfg=black ctermbg=red
  highlight GitGutterChange ctermfg=black ctermbg=yellow
'''


#------------------------------------------------------------
# オートコンプリート
#------------------------------------------------------------

[[plugins]]
#  C-g  : 前回行われた補完をキャンセル
#  C-l  : 補完候補のなかから共通する部分を補完。シェルの補完のような動き
#  C-h  : ポップアップを閉じる
#  <BS> : ポップアップを閉じる
#  C-y  : 選択している候補を確定する
#  C-e  : 選択している候補をキャンセルして閉じる
repo = 'Shougo/neocomplcache'
on_event = ['VimEnter']
hook_post_source = '''
  let g:acp_enableAtStartup=0
  let g:neocomplcache_enable_at_startup=1
  let g:neocomplcache_enable_smart_case=1
  let g:neocomplcache_enable_underbar_completion=1
  inoremap <expr><C-g> neocomplcache#undo_completion()
  inoremap <expr><C-l> neocomplcache#complete_common_string()
  inoremap <expr><C-h> neocomplcache#smart_close_popup()."\<C-h>"
  inoremap <expr><BS>  neocomplcache#smart_close_popup()."\<C-h>"
  inoremap <expr><C-y> neocomplcache#close_popup()
  inoremap <expr><C-e> neocomplcache#cancel_popup()
  autocmd vimrc FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
  autocmd vimrc FileType xml           setlocal omnifunc=xmlcomplete#CompleteTags
  autocmd vimrc FileType css           setlocal omnifunc=csscomplete#CompleteCSS
  autocmd vimrc FileType javascript    setlocal omnifunc=javascriptcomplete#CompleteJS
  autocmd vimrc FileType php           setlocal omnifunc=phpcomplete#CompletePHP
  autocmd vimrc FileType perl          setlocal omnifunc=perlcomplete#CompletePERL
  autocmd vimrc FileType python        setlocal omnifunc=pythoncomplete#Complete
  autocmd vimrc FileType c             setlocal omnifunc=ccomplete#Complete
'''


#------------------------------------------------------------
# 静的解析
#------------------------------------------------------------
[[plugins]]
repo = 'scrooloose/syntastic'
on_event = ['VimEnter']
hook_post_source = '''
  set statusline+=%#warningmsg#
  set statusline+=%{SyntasticStatuslineFlag()}
  set statusline+=%*
  let g:syntastic_always_populate_loc_list = 1
  let g:syntastic_auto_loc_list = 1
  let g:syntastic_check_on_open = 1
  let g:syntastic_check_on_wq = 0
  let g:syntastic_python_checkers = ["flake8"]
'''
