name: lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint-check:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install Required packages
      run: |
        brew install shellcheck
        pip install --upgrade pip
        pip install vim-vint

    # Lint check
    - name: Check bin/init.sh
      run: shellcheck ${GITHUB_WORKSPACE}/bin/init.sh

    - name: Check .bash_profile
      run: shellcheck ${GITHUB_WORKSPACE}/bash_profile --exclude=SC2148,SC1090

    - name: Check .bashrc
      run: shellcheck ${GITHUB_WORKSPACE}/bashrc --exclude=SC2148,SC1090

    - name: Check nvim/init.vim
      run: vint ${GITHUB_WORKSPACE}/nvim/init.vim
