name: lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint-check:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install shellcheck
      run: brew install shellcheck

    # Lint check
    - name: bin/init.sh
      run: shellcheck ${GITHUB_WORKSPACE}/bin/init.sh

    - name: .bash_profile
      run: shellcheck ${GITHUB_WORKSPACE}/bash_profile --exclude=SC2148,SC1090

    - name: .bashrc
      run: shellcheck ${GITHUB_WORKSPACE}/bashrc --exclude=SC2148,SC1090
