name: ci-linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Run init.sh
      run: sh -x ${GITHUB_WORKSPACE}/bin/init.sh

    - name: Load .bash_profile
      run: bash ~/.bash_profile; echo $?

    - name: Load .bashrc
      run: bash ~/.bashrc; echo $?
