name: linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Run init.sh
      run: |
        sh -x ${GITHUB_WORKSPACE}/bin/init.sh
        if [ ${PIPESTATUS[0]} != 0 ];then echo ${PIPESTATUS[0]};false;fi
      shell: bash

    - name: Load .bash_profile
      run: |
        bash ~/.bash_profile
        if [ ${PIPESTATUS[0]} != 0 ];then echo ${PIPESTATUS[0]};false;fi
      shell: bash

    - name: Load .bashrc
      run: |
        bash ~/.bashrc
        if [ ${PIPESTATUS[0]} != 0 ];then echo ${PIPESTATUS[0]};false;fi
      shell: bash
