name: macos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macos-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    # Error Check
    - name: Install brew packages
      run: brew bundle

    - name: Run bin/init.sh
      run: ${GITHUB_WORKSPACE}/bin/init.sh

    - name: Load .bash_profile
      run: |
        bash ~/.bash_profile 2> error.log; cat error.log
        if [ -s error.log ]; then false; fi

    - name: Load .bashrc
      run: |
        bash ~/.bashrc 2> error.log; cat error.log
        if [ -s error.log ]; then false; fi

    - name: Load .zshenv
      run: |
        zsh ~/.zshenv 2> error.log; cat error.log
        if [ -s error.log ]; then false; fi

    - name: Load .zshrc
      run: |
        # TODO: コンテナ上で zplug を入れようとすると WARNING が出るので先にインストール
        # https://github.com/zplug/zplug/issues/272
        export ZPLUG_HOME=~/.zplug
        git clone https://github.com/zplug/zplug $ZPLUG_HOME
        source $ZPLUG_HOME/init.zsh
        zplug install
        zsh ~/.zshrc 2> error.log; cat error.log
        if [ -s error.log ]; then false; fi
