name: ci-macos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: macos-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Run brew bundle
      run: brew bundle

    - name: Run init.sh
      run: sh -x ${GITHUB_WORKSPACE}/bin/init.sh

    - name: Load .bash_profile
      run: source ~/.bash_profile 1> /dev/null 2>&1 false

    - name: Load .bashrc
      run: source ~/.bashrc 1> /dev/null 2>&1 false
